# Node.js
language: node_js
node_js:
  - 6
  - 5
  - 4

# fetch newer version
sudo: required
before_install:
  - "curl -O 'https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.0/elasticsearch-2.4.0.deb' && sudo dpkg -i elasticsearch-2.4.0.deb && sudo service elasticsearch start"

# ElasticSearch takes few seconds to start
before_script:
  - sleep 10
  - curl "http://127.0.0.1:9200"

# some debug
after_script:
  - curl "http://127.0.0.1:9200"
  - curl "http://127.0.0.1:9200/phantomas_test/_search"
